name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Build
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name_root="git-wt-$tag"

          # Build everything
          dotnet publish src/wt/wt.csproj -r win-x64 -o publish/win-x64
          7z a -tzip "${release_name_root}-win-x64.zip" publish/win-x64/*

          dotnet publish src/wt/wt.csproj -r osx-arm64 -o publish/osx-arm64
          tar czvf "${release_name_root}-osx-arm64.tar.gz" publish/osx-arm64/*

          dotnet publish src/wt/wt.csproj -r linux-x64 -o publish/linux-x64
          tar czvf "${release_name_root}-linux-x64.tar.gz" publish/linux-x64/*

          # Delete output directory
          rm -r publish

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "git-wt-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}